export const GET_ARRAY2_INIT = "GET_ARRAY2_INIT";
export const GET_ARRAY2_SUCCESS = "GET_ARRAY2_SUCCESS";
export const GET_ARRAY2_FAILURE = "GET_ARRAY2_FAILURE";
export const GET_ARRAY3_INIT = "GET_ARRAY3_INIT";
export const GET_ARRAY3_SUCCESS = "GET_ARRAY3_SUCCESS";
export const GET_ARRAY3_FAILURE = "GET_ARRAY3_FAILURE";
export const UPDATE2_FORM = "UPDATE2_FORM";